//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



public partial class StatusDataContext : Microsoft.SharePoint.Linq.DataContext {
	
	#region Extensibility Method Definitions
	partial void OnCreated();
	#endregion
	
	public StatusDataContext(string requestUrl) : 
			base(requestUrl) {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Outages")]
	public Microsoft.SharePoint.Linq.EntityList<OutagesItem> Outages {
		get {
			return this.GetList<OutagesItem>("Outages");
		}
	}
	
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Subscriptions")]
	public Microsoft.SharePoint.Linq.EntityList<SubscriptionsItem> Subscriptions {
		get {
			return this.GetList<SubscriptionsItem>("Subscriptions");
		}
	}
	
	/// <summary>
	/// List of systems which we will report against
	/// </summary>
	[Microsoft.SharePoint.Linq.ListAttribute(Name="Systems")]
	public Microsoft.SharePoint.Linq.EntityList<SystemsItem> Systems {
		get {
			return this.GetList<SystemsItem>("Systems");
		}
	}
}

/// <summary>
/// Create a new list item.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Item", Id="0x01")]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(OutagesItem))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(SubscriptionsItem))]
[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(SystemsItem))]
public partial class Item : Microsoft.SharePoint.Linq.ITrackEntityState, Microsoft.SharePoint.Linq.ITrackOriginalValues, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {
	
	private System.Nullable<int> _id;
	
	private System.Nullable<int> _version;
	
	private string _path;
	
	private Microsoft.SharePoint.Linq.EntityState _entityState;
	
	private System.Collections.Generic.IDictionary<string, object> _originalValues;
	
	private string _title;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion

	Microsoft.SharePoint.Linq.EntityState Microsoft.SharePoint.Linq.ITrackEntityState.EntityState {
		get {
			return this._entityState;
		}
		set {
			if ((value != this._entityState)) {
				this._entityState = value;
			}
		}
	}

	System.Collections.Generic.IDictionary<string, object> Microsoft.SharePoint.Linq.ITrackOriginalValues.OriginalValues {
		get {
			if ((null == this._originalValues)) {
				this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
			}
			return this._originalValues;
		}
	}
	
	public Item() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ID", Storage="_id", ReadOnly=true, FieldType="Counter")]
	public System.Nullable<int> Id {
		get {
			return this._id;
		}
		set {
			if ((value != this._id)) {
				this.OnPropertyChanging("Id", this._id);
				this._id = value;
				this.OnPropertyChanged("Id");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="owshiddenversion", Storage="_version", ReadOnly=true, FieldType="Integer")]
	public System.Nullable<int> Version {
		get {
			return this._version;
		}
		set {
			if ((value != this._version)) {
				this.OnPropertyChanging("Version", this._version);
				this._version = value;
				this.OnPropertyChanged("Version");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FileDirRef", Storage="_path", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
	public string Path {
		get {
			return this._path;
		}
		set {
			if ((value != this._path)) {
				this.OnPropertyChanging("Path", this._path);
				this._path = value;
				this.OnPropertyChanged("Path");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Title", Storage="_title", Required=true, FieldType="Text")]
	public virtual string Title {
		get {
			return this._title;
		}
		set {
			if ((value != this._title)) {
				this.OnPropertyChanging("Title", this._title);
				this._title = value;
				this.OnPropertyChanged("Title");
			}
		}
	}
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	protected virtual void OnPropertyChanged(string propertyName) {
		if ((null != this.PropertyChanged)) {
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	protected virtual void OnPropertyChanging(string propertyName, object value) {
		if ((null == this._originalValues)) {
			this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
		}
		if ((false == this._originalValues.ContainsKey(propertyName))) {
			this._originalValues.Add(propertyName, value);
		}
		if ((null != this.PropertyChanging)) {
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
}

/// <summary>
/// Create a new list item.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Item", Id="0x01", List="Outages")]
public partial class OutagesItem : Item {
	
	private string _impactedSystems;
	
	private string _offices;
	
	private System.Nullable<System.DateTime> _start;
	
	private System.Nullable<System.DateTime> _end;
	
	private string _details;
	
	private string _trackingRef;
	
	private System.Nullable<Region> _region;
	
	private System.Nullable<Defcom> _defcom;
	
	private Microsoft.SharePoint.Linq.EntityRef<SystemsItem> _system;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public OutagesItem() {
		this._system = new Microsoft.SharePoint.Linq.EntityRef<SystemsItem>();
		this._system.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<SystemsItem>>(this.OnSystemSync);
		this._system.OnChanged += new System.EventHandler(this.OnSystemChanged);
		this._system.OnChanging += new System.EventHandler(this.OnSystemChanging);
		this.OnCreated();
	}
	
	/// <summary>
	/// Description of the sub category impacted
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Subcategory", Storage="_impactedSystems", FieldType="Text")]
	public string ImpactedSystems {
		get {
			return this._impactedSystems;
		}
		set {
			if ((value != this._impactedSystems)) {
				this.OnPropertyChanging("ImpactedSystems", this._impactedSystems);
				this._impactedSystems = value;
				this.OnPropertyChanged("ImpactedSystems");
			}
		}
	}
	
	/// <summary>
	/// Offices affected
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Offices", Storage="_offices", FieldType="Text")]
	public string Offices {
		get {
			return this._offices;
		}
		set {
			if ((value != this._offices)) {
				this.OnPropertyChanging("Offices", this._offices);
				this._offices = value;
				this.OnPropertyChanged("Offices");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Start", Storage="_start", Required=true, FieldType="DateTime")]
	public System.Nullable<System.DateTime> Start {
		get {
			return this._start;
		}
		set {
			if ((value != this._start)) {
				this.OnPropertyChanging("Start", this._start);
				this._start = value;
				this.OnPropertyChanged("Start");
			}
		}
	}
	
	/// <summary>
	/// Problem end time
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="End", Storage="_end", FieldType="DateTime")]
	public System.Nullable<System.DateTime> End {
		get {
			return this._end;
		}
		set {
			if ((value != this._end)) {
				this.OnPropertyChanging("End", this._end);
				this._end = value;
				this.OnPropertyChanged("End");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Details", Storage="_details", FieldType="Note")]
	public string Details {
		get {
			return this._details;
		}
		set {
			if ((value != this._details)) {
				this.OnPropertyChanging("Details", this._details);
				this._details = value;
				this.OnPropertyChanged("Details");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Ticket", Storage="_trackingRef", FieldType="Text")]
	public string TrackingRef {
		get {
			return this._trackingRef;
		}
		set {
			if ((value != this._trackingRef)) {
				this.OnPropertyChanging("TrackingRef", this._trackingRef);
				this._trackingRef = value;
				this.OnPropertyChanged("TrackingRef");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Region", Storage="_region", FieldType="MultiChoice")]
	public System.Nullable<Region> Region {
		get {
			return this._region;
		}
		set {
			if ((value != this._region)) {
				this.OnPropertyChanging("Region", this._region);
				this._region = value;
				this.OnPropertyChanged("Region");
			}
		}
	}
	
	/// <summary>
	/// 1 - Total Outage 2 - Partial Outage w Workaround 3 - Some Subsystems Impacted 4 - Planned Outage in Progress 
	/// </summary>
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Defcom", Storage="_defcom", FieldType="Choice")]
	public System.Nullable<Defcom> Defcom {
		get {
			return this._defcom;
		}
		set {
			if ((value != this._defcom)) {
				this.OnPropertyChanging("Defcom", this._defcom);
				this._defcom = value;
				this.OnPropertyChanged("Defcom");
			}
		}
	}
	
	/// <summary>
	/// System experiencing a problem
	/// </summary>
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="System", Storage="_system", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Systems")]
	public SystemsItem System {
		get {
			return this._system.GetEntity();
		}
		set {
			this._system.SetEntity(value);
		}
	}
	
	private void OnSystemChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("System", this._system.Clone());
	}
	
	private void OnSystemChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("System");
	}
	
	private void OnSystemSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<SystemsItem> e) {
		if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
			e.Item.OutagesItem.Add(this);
		}
		else {
			e.Item.OutagesItem.Remove(this);
		}
	}
}

/// <summary>
/// Create a new list item.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Item", Id="0x01", List="Subscriptions")]
public partial class SubscriptionsItem : Item {
	
	private System.Nullable<bool> _col1;
	
	private System.Nullable<bool> _col2;
	
	private System.Nullable<bool> _col3;
	
	private System.Nullable<bool> _col4;
	
	private System.Nullable<bool> _col5;
	
	private System.Nullable<bool> _col6;
	
	private System.Nullable<bool> _col7;
	
	private System.Nullable<bool> _col8;
	
	private System.Nullable<bool> _col9;
	
	private System.Nullable<bool> _col10;
	
	private System.Nullable<bool> _col11;
	
	private System.Nullable<bool> _col12;
	
	private System.Nullable<bool> _col13;
	
	private System.Nullable<bool> _col14;
	
	private System.Nullable<bool> _col15;
	
	private System.Nullable<bool> _col16;
	
	private System.Nullable<bool> _col17;
	
	private System.Nullable<bool> _col18;
	
	private System.Nullable<bool> _col19;
	
	private System.Nullable<bool> _col20;
	
	private System.Nullable<bool> _col21;
	
	private System.Nullable<bool> _col22;
	
	private System.Nullable<bool> _col23;
	
	private System.Nullable<bool> _col24;
	
	private System.Nullable<bool> _col25;
	
	private System.Nullable<bool> _col26;
	
	private System.Nullable<bool> _col27;
	
	private System.Nullable<bool> _col28;
	
	private System.Nullable<bool> _col29;
	
	private System.Nullable<bool> _col30;
	
	private System.Nullable<bool> _col31;
	
	private System.Nullable<bool> _col32;
	
	private System.Nullable<bool> _col33;
	
	private System.Nullable<bool> _col34;
	
	private System.Nullable<bool> _col35;
	
	private System.Nullable<bool> _col36;
	
	private System.Nullable<bool> _col37;
	
	private System.Nullable<bool> _col38;
	
	private System.Nullable<bool> _col39;
	
	private System.Nullable<bool> _col40;
	
	private System.Nullable<bool> _col41;
	
	private System.Nullable<bool> _col42;
	
	private System.Nullable<bool> _col43;
	
	private System.Nullable<bool> _col44;
	
	private System.Nullable<bool> _col45;
	
	private System.Nullable<bool> _col46;
	
	private System.Nullable<bool> _col47;
	
	private System.Nullable<bool> _col48;
	
	private System.Nullable<bool> _col49;
	
	private System.Nullable<bool> _col50;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public SubscriptionsItem() {
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol1", Storage="_col1", FieldType="Boolean")]
	public System.Nullable<bool> Col1 {
		get {
			return this._col1;
		}
		set {
			if ((value != this._col1)) {
				this.OnPropertyChanging("Col1", this._col1);
				this._col1 = value;
				this.OnPropertyChanged("Col1");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol2", Storage="_col2", FieldType="Boolean")]
	public System.Nullable<bool> Col2 {
		get {
			return this._col2;
		}
		set {
			if ((value != this._col2)) {
				this.OnPropertyChanging("Col2", this._col2);
				this._col2 = value;
				this.OnPropertyChanged("Col2");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol3", Storage="_col3", FieldType="Boolean")]
	public System.Nullable<bool> Col3 {
		get {
			return this._col3;
		}
		set {
			if ((value != this._col3)) {
				this.OnPropertyChanging("Col3", this._col3);
				this._col3 = value;
				this.OnPropertyChanged("Col3");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol4", Storage="_col4", FieldType="Boolean")]
	public System.Nullable<bool> Col4 {
		get {
			return this._col4;
		}
		set {
			if ((value != this._col4)) {
				this.OnPropertyChanging("Col4", this._col4);
				this._col4 = value;
				this.OnPropertyChanged("Col4");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol5", Storage="_col5", FieldType="Boolean")]
	public System.Nullable<bool> Col5 {
		get {
			return this._col5;
		}
		set {
			if ((value != this._col5)) {
				this.OnPropertyChanging("Col5", this._col5);
				this._col5 = value;
				this.OnPropertyChanged("Col5");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol6", Storage="_col6", FieldType="Boolean")]
	public System.Nullable<bool> Col6 {
		get {
			return this._col6;
		}
		set {
			if ((value != this._col6)) {
				this.OnPropertyChanging("Col6", this._col6);
				this._col6 = value;
				this.OnPropertyChanged("Col6");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol7", Storage="_col7", FieldType="Boolean")]
	public System.Nullable<bool> Col7 {
		get {
			return this._col7;
		}
		set {
			if ((value != this._col7)) {
				this.OnPropertyChanging("Col7", this._col7);
				this._col7 = value;
				this.OnPropertyChanged("Col7");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol8", Storage="_col8", FieldType="Boolean")]
	public System.Nullable<bool> Col8 {
		get {
			return this._col8;
		}
		set {
			if ((value != this._col8)) {
				this.OnPropertyChanging("Col8", this._col8);
				this._col8 = value;
				this.OnPropertyChanged("Col8");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol9", Storage="_col9", FieldType="Boolean")]
	public System.Nullable<bool> Col9 {
		get {
			return this._col9;
		}
		set {
			if ((value != this._col9)) {
				this.OnPropertyChanging("Col9", this._col9);
				this._col9 = value;
				this.OnPropertyChanged("Col9");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol10", Storage="_col10", FieldType="Boolean")]
	public System.Nullable<bool> Col10 {
		get {
			return this._col10;
		}
		set {
			if ((value != this._col10)) {
				this.OnPropertyChanging("Col10", this._col10);
				this._col10 = value;
				this.OnPropertyChanged("Col10");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol11", Storage="_col11", FieldType="Boolean")]
	public System.Nullable<bool> Col11 {
		get {
			return this._col11;
		}
		set {
			if ((value != this._col11)) {
				this.OnPropertyChanging("Col11", this._col11);
				this._col11 = value;
				this.OnPropertyChanged("Col11");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol12", Storage="_col12", FieldType="Boolean")]
	public System.Nullable<bool> Col12 {
		get {
			return this._col12;
		}
		set {
			if ((value != this._col12)) {
				this.OnPropertyChanging("Col12", this._col12);
				this._col12 = value;
				this.OnPropertyChanged("Col12");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol13", Storage="_col13", FieldType="Boolean")]
	public System.Nullable<bool> Col13 {
		get {
			return this._col13;
		}
		set {
			if ((value != this._col13)) {
				this.OnPropertyChanging("Col13", this._col13);
				this._col13 = value;
				this.OnPropertyChanged("Col13");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol14", Storage="_col14", FieldType="Boolean")]
	public System.Nullable<bool> Col14 {
		get {
			return this._col14;
		}
		set {
			if ((value != this._col14)) {
				this.OnPropertyChanging("Col14", this._col14);
				this._col14 = value;
				this.OnPropertyChanged("Col14");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol15", Storage="_col15", FieldType="Boolean")]
	public System.Nullable<bool> Col15 {
		get {
			return this._col15;
		}
		set {
			if ((value != this._col15)) {
				this.OnPropertyChanging("Col15", this._col15);
				this._col15 = value;
				this.OnPropertyChanged("Col15");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol16", Storage="_col16", FieldType="Boolean")]
	public System.Nullable<bool> Col16 {
		get {
			return this._col16;
		}
		set {
			if ((value != this._col16)) {
				this.OnPropertyChanging("Col16", this._col16);
				this._col16 = value;
				this.OnPropertyChanged("Col16");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol17", Storage="_col17", FieldType="Boolean")]
	public System.Nullable<bool> Col17 {
		get {
			return this._col17;
		}
		set {
			if ((value != this._col17)) {
				this.OnPropertyChanging("Col17", this._col17);
				this._col17 = value;
				this.OnPropertyChanged("Col17");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol18", Storage="_col18", FieldType="Boolean")]
	public System.Nullable<bool> Col18 {
		get {
			return this._col18;
		}
		set {
			if ((value != this._col18)) {
				this.OnPropertyChanging("Col18", this._col18);
				this._col18 = value;
				this.OnPropertyChanged("Col18");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol19", Storage="_col19", FieldType="Boolean")]
	public System.Nullable<bool> Col19 {
		get {
			return this._col19;
		}
		set {
			if ((value != this._col19)) {
				this.OnPropertyChanging("Col19", this._col19);
				this._col19 = value;
				this.OnPropertyChanged("Col19");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol20", Storage="_col20", FieldType="Boolean")]
	public System.Nullable<bool> Col20 {
		get {
			return this._col20;
		}
		set {
			if ((value != this._col20)) {
				this.OnPropertyChanging("Col20", this._col20);
				this._col20 = value;
				this.OnPropertyChanged("Col20");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol21", Storage="_col21", FieldType="Boolean")]
	public System.Nullable<bool> Col21 {
		get {
			return this._col21;
		}
		set {
			if ((value != this._col21)) {
				this.OnPropertyChanging("Col21", this._col21);
				this._col21 = value;
				this.OnPropertyChanged("Col21");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol22", Storage="_col22", FieldType="Boolean")]
	public System.Nullable<bool> Col22 {
		get {
			return this._col22;
		}
		set {
			if ((value != this._col22)) {
				this.OnPropertyChanging("Col22", this._col22);
				this._col22 = value;
				this.OnPropertyChanged("Col22");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol23", Storage="_col23", FieldType="Boolean")]
	public System.Nullable<bool> Col23 {
		get {
			return this._col23;
		}
		set {
			if ((value != this._col23)) {
				this.OnPropertyChanging("Col23", this._col23);
				this._col23 = value;
				this.OnPropertyChanged("Col23");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol24", Storage="_col24", FieldType="Boolean")]
	public System.Nullable<bool> Col24 {
		get {
			return this._col24;
		}
		set {
			if ((value != this._col24)) {
				this.OnPropertyChanging("Col24", this._col24);
				this._col24 = value;
				this.OnPropertyChanged("Col24");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol25", Storage="_col25", FieldType="Boolean")]
	public System.Nullable<bool> Col25 {
		get {
			return this._col25;
		}
		set {
			if ((value != this._col25)) {
				this.OnPropertyChanging("Col25", this._col25);
				this._col25 = value;
				this.OnPropertyChanged("Col25");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol26", Storage="_col26", FieldType="Boolean")]
	public System.Nullable<bool> Col26 {
		get {
			return this._col26;
		}
		set {
			if ((value != this._col26)) {
				this.OnPropertyChanging("Col26", this._col26);
				this._col26 = value;
				this.OnPropertyChanged("Col26");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol27", Storage="_col27", FieldType="Boolean")]
	public System.Nullable<bool> Col27 {
		get {
			return this._col27;
		}
		set {
			if ((value != this._col27)) {
				this.OnPropertyChanging("Col27", this._col27);
				this._col27 = value;
				this.OnPropertyChanged("Col27");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol28", Storage="_col28", FieldType="Boolean")]
	public System.Nullable<bool> Col28 {
		get {
			return this._col28;
		}
		set {
			if ((value != this._col28)) {
				this.OnPropertyChanging("Col28", this._col28);
				this._col28 = value;
				this.OnPropertyChanged("Col28");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol29", Storage="_col29", FieldType="Boolean")]
	public System.Nullable<bool> Col29 {
		get {
			return this._col29;
		}
		set {
			if ((value != this._col29)) {
				this.OnPropertyChanging("Col29", this._col29);
				this._col29 = value;
				this.OnPropertyChanged("Col29");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol30", Storage="_col30", FieldType="Boolean")]
	public System.Nullable<bool> Col30 {
		get {
			return this._col30;
		}
		set {
			if ((value != this._col30)) {
				this.OnPropertyChanging("Col30", this._col30);
				this._col30 = value;
				this.OnPropertyChanged("Col30");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol31", Storage="_col31", FieldType="Boolean")]
	public System.Nullable<bool> Col31 {
		get {
			return this._col31;
		}
		set {
			if ((value != this._col31)) {
				this.OnPropertyChanging("Col31", this._col31);
				this._col31 = value;
				this.OnPropertyChanged("Col31");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol32", Storage="_col32", FieldType="Boolean")]
	public System.Nullable<bool> Col32 {
		get {
			return this._col32;
		}
		set {
			if ((value != this._col32)) {
				this.OnPropertyChanging("Col32", this._col32);
				this._col32 = value;
				this.OnPropertyChanged("Col32");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol33", Storage="_col33", FieldType="Boolean")]
	public System.Nullable<bool> Col33 {
		get {
			return this._col33;
		}
		set {
			if ((value != this._col33)) {
				this.OnPropertyChanging("Col33", this._col33);
				this._col33 = value;
				this.OnPropertyChanged("Col33");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol34", Storage="_col34", FieldType="Boolean")]
	public System.Nullable<bool> Col34 {
		get {
			return this._col34;
		}
		set {
			if ((value != this._col34)) {
				this.OnPropertyChanging("Col34", this._col34);
				this._col34 = value;
				this.OnPropertyChanged("Col34");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol35", Storage="_col35", FieldType="Boolean")]
	public System.Nullable<bool> Col35 {
		get {
			return this._col35;
		}
		set {
			if ((value != this._col35)) {
				this.OnPropertyChanging("Col35", this._col35);
				this._col35 = value;
				this.OnPropertyChanged("Col35");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol36", Storage="_col36", FieldType="Boolean")]
	public System.Nullable<bool> Col36 {
		get {
			return this._col36;
		}
		set {
			if ((value != this._col36)) {
				this.OnPropertyChanging("Col36", this._col36);
				this._col36 = value;
				this.OnPropertyChanged("Col36");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol37", Storage="_col37", FieldType="Boolean")]
	public System.Nullable<bool> Col37 {
		get {
			return this._col37;
		}
		set {
			if ((value != this._col37)) {
				this.OnPropertyChanging("Col37", this._col37);
				this._col37 = value;
				this.OnPropertyChanged("Col37");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol38", Storage="_col38", FieldType="Boolean")]
	public System.Nullable<bool> Col38 {
		get {
			return this._col38;
		}
		set {
			if ((value != this._col38)) {
				this.OnPropertyChanging("Col38", this._col38);
				this._col38 = value;
				this.OnPropertyChanged("Col38");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol39", Storage="_col39", FieldType="Boolean")]
	public System.Nullable<bool> Col39 {
		get {
			return this._col39;
		}
		set {
			if ((value != this._col39)) {
				this.OnPropertyChanging("Col39", this._col39);
				this._col39 = value;
				this.OnPropertyChanged("Col39");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol40", Storage="_col40", FieldType="Boolean")]
	public System.Nullable<bool> Col40 {
		get {
			return this._col40;
		}
		set {
			if ((value != this._col40)) {
				this.OnPropertyChanging("Col40", this._col40);
				this._col40 = value;
				this.OnPropertyChanged("Col40");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol41", Storage="_col41", FieldType="Boolean")]
	public System.Nullable<bool> Col41 {
		get {
			return this._col41;
		}
		set {
			if ((value != this._col41)) {
				this.OnPropertyChanging("Col41", this._col41);
				this._col41 = value;
				this.OnPropertyChanged("Col41");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol42", Storage="_col42", FieldType="Boolean")]
	public System.Nullable<bool> Col42 {
		get {
			return this._col42;
		}
		set {
			if ((value != this._col42)) {
				this.OnPropertyChanging("Col42", this._col42);
				this._col42 = value;
				this.OnPropertyChanged("Col42");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol43", Storage="_col43", FieldType="Boolean")]
	public System.Nullable<bool> Col43 {
		get {
			return this._col43;
		}
		set {
			if ((value != this._col43)) {
				this.OnPropertyChanging("Col43", this._col43);
				this._col43 = value;
				this.OnPropertyChanged("Col43");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol44", Storage="_col44", FieldType="Boolean")]
	public System.Nullable<bool> Col44 {
		get {
			return this._col44;
		}
		set {
			if ((value != this._col44)) {
				this.OnPropertyChanging("Col44", this._col44);
				this._col44 = value;
				this.OnPropertyChanged("Col44");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol45", Storage="_col45", FieldType="Boolean")]
	public System.Nullable<bool> Col45 {
		get {
			return this._col45;
		}
		set {
			if ((value != this._col45)) {
				this.OnPropertyChanging("Col45", this._col45);
				this._col45 = value;
				this.OnPropertyChanged("Col45");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol46", Storage="_col46", FieldType="Boolean")]
	public System.Nullable<bool> Col46 {
		get {
			return this._col46;
		}
		set {
			if ((value != this._col46)) {
				this.OnPropertyChanging("Col46", this._col46);
				this._col46 = value;
				this.OnPropertyChanged("Col46");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol47", Storage="_col47", FieldType="Boolean")]
	public System.Nullable<bool> Col47 {
		get {
			return this._col47;
		}
		set {
			if ((value != this._col47)) {
				this.OnPropertyChanging("Col47", this._col47);
				this._col47 = value;
				this.OnPropertyChanged("Col47");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol48", Storage="_col48", FieldType="Boolean")]
	public System.Nullable<bool> Col48 {
		get {
			return this._col48;
		}
		set {
			if ((value != this._col48)) {
				this.OnPropertyChanging("Col48", this._col48);
				this._col48 = value;
				this.OnPropertyChanged("Col48");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol49", Storage="_col49", FieldType="Boolean")]
	public System.Nullable<bool> Col49 {
		get {
			return this._col49;
		}
		set {
			if ((value != this._col49)) {
				this.OnPropertyChanging("Col49", this._col49);
				this._col49 = value;
				this.OnPropertyChanged("Col49");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="_x0043_ol50", Storage="_col50", FieldType="Boolean")]
	public System.Nullable<bool> Col50 {
		get {
			return this._col50;
		}
		set {
			if ((value != this._col50)) {
				this.OnPropertyChanging("Col50", this._col50);
				this._col50 = value;
				this.OnPropertyChanged("Col50");
			}
		}
	}
}

/// <summary>
/// Create a new list item.
/// </summary>
[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Item", Id="0x01", List="Systems")]
public partial class SystemsItem : Item {
	
	private string _description;
	
	private System.Nullable<double> _sortOrder;
	
	private System.Nullable<Category> _category;
	
	private Microsoft.SharePoint.Linq.EntitySet<OutagesItem> _outagesItem;
	
	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate();
	partial void OnCreated();
	#endregion
	
	public SystemsItem() {
		this._outagesItem = new Microsoft.SharePoint.Linq.EntitySet<OutagesItem>();
		this._outagesItem.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<OutagesItem>>(this.OnOutagesItemSync);
		this._outagesItem.OnChanged += new System.EventHandler(this.OnOutagesItemChanged);
		this._outagesItem.OnChanging += new System.EventHandler(this.OnOutagesItemChanging);
		this.OnCreated();
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Description", Storage="_description", FieldType="Note")]
	public string Description {
		get {
			return this._description;
		}
		set {
			if ((value != this._description)) {
				this.OnPropertyChanging("Description", this._description);
				this._description = value;
				this.OnPropertyChanged("Description");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="SortOrder", Storage="_sortOrder", FieldType="Number")]
	public System.Nullable<double> SortOrder {
		get {
			return this._sortOrder;
		}
		set {
			if ((value != this._sortOrder)) {
				this.OnPropertyChanging("SortOrder", this._sortOrder);
				this._sortOrder = value;
				this.OnPropertyChanged("SortOrder");
			}
		}
	}
	
	[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Category", Storage="_category", FieldType="Choice")]
	public System.Nullable<Category> Category {
		get {
			return this._category;
		}
		set {
			if ((value != this._category)) {
				this.OnPropertyChanging("Category", this._category);
				this._category = value;
				this.OnPropertyChanged("Category");
			}
		}
	}
	
	/// <summary>
	/// System experiencing a problem
	/// </summary>
	[Microsoft.SharePoint.Linq.AssociationAttribute(Name="System", Storage="_outagesItem", ReadOnly=true, MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Backward, List="Outages")]
	public Microsoft.SharePoint.Linq.EntitySet<OutagesItem> OutagesItem {
		get {
			return this._outagesItem;
		}
		set {
			this._outagesItem.Assign(value);
		}
	}
	
	private void OnOutagesItemChanging(object sender, System.EventArgs e) {
		this.OnPropertyChanging("OutagesItem", this._outagesItem.Clone());
	}
	
	private void OnOutagesItemChanged(object sender, System.EventArgs e) {
		this.OnPropertyChanged("OutagesItem");
	}
	
	private void OnOutagesItemSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<OutagesItem> e) {
		if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
			e.Item.System = this;
		}
		else {
			e.Item.System = null;
		}
	}
}

[System.FlagsAttribute()]
public enum Region : int {
	
	None = 0,
	
	Invalid = 1,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="AMER")]
	AMER = 2,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="EMEA")]
	EMEA = 4,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="APAC")]
	APAC = 8,
}

public enum Defcom : int {
	
	None = 0,
	
	Invalid = 1,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="1")]
	_1 = 2,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="2")]
	_2 = 4,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="3")]
	_3 = 8,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="4")]
	_4 = 16,
}

public enum Category : int {
	
	None = 0,
	
	Invalid = 1,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Infrastructure")]
	Infrastructure = 2,
	
	[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Applications")]
	Applications = 4,
}
